# Generated by Django 3.2.9 on 2021-12-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_projects_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='background',
            field=models.URLField(blank=True),
        ),
    ]
