# Generated by Django 3.2.9 on 2021-12-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_background_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myphoto',
            name='myphoto',
            field=models.URLField(blank=True, null=True),
        ),
    ]
