# Generated by Django 3.2.9 on 2021-12-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_myphoto_myphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
